### ISSUE TITLE
VM no longer builds properly

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#1022]
Starting from a fresh clone, when I try and do an initial `vagrant up` I get the following error:

```
   default: ===============
    default: INSTALLING PERU
    default: ---------------
    default: Downloading/unpacking peru
    default:   Running setup.py (path:/tmp/pip_build_root/peru/setup.py) egg_info for package peru
    default:     fastentrypoints
    default:     Traceback (most recent call last):
    default:       File "<string>", line 17, in <module>
    default:       File "/tmp/pip_build_root/peru/setup.py", line 56, in <module>
    default:         install_requires=get_install_requires(),
    default:       File "/tmp/pip_build_root/peru/setup.py", line 39, in get_install_requires
    default:         raise RuntimeError('The minimum supported Python version is 3.5.')
    default:     RuntimeError: The minimum supported Python version is 3.5.
    default:     Complete output from command python setup.py egg_info:
    default:     fastentrypoints
    default:
    default: Traceback (most recent call last):
    default:
    default:   File "<string>", line 17, in <module>
    default:
    default:   File "/tmp/pip_build_root/peru/setup.py", line 56, in <module>
    default:
    default:     install_requires=get_install_requires(),
    default:
    default:   File "/tmp/pip_build_root/peru/setup.py", line 39, in get_install_requires
    default:
    default:     raise RuntimeError('The minimum supported Python version is 3.5.')
    default:
    default: RuntimeError: The minimum supported Python version is 3.5.
    default:
    default: ----------------------------------------
    default: Cleaning up...
    default: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/peru
    default: Storing debug log for failure in /root/.pip/pip.log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.   default: ===============
    default: INSTALLING PERU
    default: ---------------
    default: Downloading/unpacking peru
    default:   Running setup.py (path:/tmp/pip_build_root/peru/setup.py) egg_info for package peru
    default:     fastentrypoints
    default:     Traceback (most recent call last):
    default:       File "<string>", line 17, in <module>
    default:       File "/tmp/pip_build_root/peru/setup.py", line 56, in <module>
    default:         install_requires=get_install_requires(),
    default:       File "/tmp/pip_build_root/peru/setup.py", line 39, in get_install_requires
    default:         raise RuntimeError('The minimum supported Python version is 3.5.')
    default:     RuntimeError: The minimum supported Python version is 3.5.
    default:     Complete output from command python setup.py egg_info:
    default:     fastentrypoints
    default:
    default: Traceback (most recent call last):
    default:
    default:   File "<string>", line 17, in <module>
    default:
    default:   File "/tmp/pip_build_root/peru/setup.py", line 56, in <module>
    default:
    default:     install_requires=get_install_requires(),
    default:
    default:   File "/tmp/pip_build_root/peru/setup.py", line 39, in get_install_requires
    default:
    default:     raise RuntimeError('The minimum supported Python version is 3.5.')
    default:
    default: RuntimeError: The minimum supported Python version is 3.5.
    default:
    default: ----------------------------------------
    default: Cleaning up...
    default: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/peru
    default: Storing debug log for failure in /root/.pip/pip.log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by yalisassoon** [comment]
More info and some steps towards resolution can be found in: https://snowplow.zendesk.com/agent/tickets/12971

**Comment by jbeemster** [comment]
Closing as we have now moved away from the VM approach!
